### ISSUE TITLE
I'm getting 2 issues running the examples provided [ File is not a zip file , Please make sure the selected font name is correct!]

### ISSUE THREAD

**Issue by Sue-Fwl** [iamaziz/ar_wordcloud#2]
Greetings,

Thanks for providing this lib!

This is the error I'm getting when running the examples after installing the lib:

`
  File "\lib\zipfile.py", line 1222, in __init__
    self._RealGetContents()

  File "\lib\zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")

BadZipFile: File is not a zip file`

-------------------------------
The second one is after running - awc = ArabicWordCloud() - , I tried it with the BG property added and without it and with the Font property as the example suggested but still I got the same error:
`
  File "lib\site-packages\ar_wordcloud\ar_wordcloud.py", line 24, in __init__
    self.fonts = ArabicFonts(font=font)

  File "\lib\site-packages\ar_wordcloud\_fonts.py", line 30, in __init__
    assert font in self.available_fonts or font is "", self._font_error

AssertionError: بالله أتأكد ان اسم الخط المُدخل صحيح
Please make sure the selected font name is correct!
`

**Comment by iamaziz** [comment]
Hey, thanks for trying it out! It seems the fonts were not downloaded correctly. What OS are you using? And could you try to run this: 

```python
>>> from ar_wordcloud._fonts import ArabicFont
>>> fonts = ArabicFonts(font="NotoNaskhArabic-Regular.ttf")
>>> fonts
```

**Comment by Sue-Fwl** [comment]
I'm using Win 10.

Tried it and got this error:
```python
 from ar_wordcloud._fonts import ArabicFont
Traceback (most recent call last):

  File "<ipython-input-5-34f575972f5e>", line 1, in <module>
    from ar_wordcloud._fonts import ArabicFont

ImportError: cannot import name 'ArabicFont' from 'ar_wordcloud._fonts' (\lib\site-packages\ar_wordcloud\_fonts.py)
```

**Comment by iamaziz** [comment]
Windows may have a different way of handling zip files. I don't have access to Windows to test this, unfortunately.
